### ISSUE TITLE
Configure VPN on buildroot. 

### ISSUE THREAD

**Issue by AydBlot** [cu-ecen-5013/final-project-AydBlot#5]
Set up openVPN files and ensure the VPN can be connected to by a client.

DoD: VPN is functional when on the raspberry pi. A client can successfully connect to the server hosted on Pi.

**Comment by AydBlot** [comment]
OpenVPN and required files installed: https://github.com/cu-ecen-5013/final-project-AydBlot/commit/9e83667727f8843cffb0735efffa9076912a7522

**Comment by steveantony5** [comment]
@AydBlot  Can you please explain how do you verify that the vpn  is functional? This info has to be in dod
